apiVersion: batch/v1
kind: Job
metadata:
  name: pg-logical-resotre
spec:
  template:
    spec:
      containers:
      - name: backup
        image: sysbind/pg-logical-backup
        command: ["sleep"]
        args: ["2h"]
        env:
          - name: PG_VERSION
            value: "12"
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: postgres.maas-dbstage.credentials.postgresql.acid.zalan.do
                key: user
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres.maas-dbstage.credentials.postgresql.acid.zalan.do
                key: password
          - name: PGHOST
            value: "maas-dbstage"
          - name: ENVOY_SIGNAL_SHUTDOWN
            value: "true"
          - name: AZURE_STORAGE_ACCOUNT
            value: moodlesaasprod
          - name: AZURE_STORAGE_KEY
            value: JbfMQgaBSRSo161/8kVGpru02efklklq6JD4OX/hmvnu59IDZ10UIDwzYIUdmugmzUVRM+BUh8+GPrNE4GermA==
          - name: AZURE_CONTAINER_NAME
            value: pgbackup
      restartPolicy: Never

