apiVersion: batch/v1
kind: Job
metadata:
  name: pg-logical-backup
spec:
  template:
    spec:
      containers:
      - name: backup
        image: sysbind/pg-logical-backup
        env:
          - name: PG_VERSION
            value: "13"
          - name: PGUSER
            value: "postgres"
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres.maas-main.credentials.postgresql.acid.zalan.do
                key: password
          - name: PGHOST
            value: "maas-main-repl"
          - name: GCS_BUCKET
            value: "gs://maas-pg-backup"
          - name: GCS_KEYFILE
            value: "/var/run/secrets/gcs/gcskey.json"
        volumeMounts:
        - name: gcskey
          mountPath: "/var/run/secrets/gcs"
      volumes:
        - name: gcskey
          secret:
            secretName: pg-logical-backup-gcs-keyfile
      restartPolicy: Never

